services:
  discovery-service:
    build:
      context: .
      dockerfile: discovery_service/Dockerfile
    image: phucngo249/discovery-service:latest
    container_name: discovery-service-app
    restart: always
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8761 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - classroom-network

  api-gateway:
    build:
      context: .
      dockerfile: gateway_service/Dockerfile
    image: phucngo249/gateway-service:latest
    container_name: gateway-service-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - EUREKA_URL=http://discovery-service-app:8761/eureka/
      - KEYCLOAK_URL=${KEYCLOAK_URL:-http://localhost:8181}
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - classroom-network

  postgres-user-db:
    image: postgres:15-alpine
    container_name: postgres-user-container
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=user_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  postgres-class-db:
    image: postgres:15-alpine
    container_name: postgres-class-container
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=class_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d class_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_class_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  postgres-assignment-db:
    image: postgres:15-alpine
    container_name: postgres-assignment-container
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=assignment_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d assignment_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_assignment_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecretpassword
    volumes:
      - minio_data:/data
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - classroom-network

  loki:
    image: grafana/loki:2.9.4
    container_name: loki-storage
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - classroom-network

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus-server
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - classroom-network

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo-tracer
    restart: always
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo/tempo.yml
    ports:
      - "3200:3200"
      - "9411:9411"
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - classroom-network

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana-dashboard
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    deploy:
      resources:
        limits:
          memory: 250M
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - classroom-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: phucngo249/user-service:latest
    container_name: user-service-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - DB_HOST=postgres-user-db
      - DB_PORT=5432
      - DB_NAME=user_service
      - DB_USER=postgres
      - DB_PASSWORD=123
      - APP_JWT_SECRET=3c963655447b567565b90214e9f7f0bc62e1e07b7134017326dfbf0800b6ed5b
      - EUREKA_URL=http://discovery-service-app:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=user-service-app
    depends_on:
      postgres-user-db:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - classroom-network

  class-service:
    build:
      context: .
      dockerfile: class_service/Dockerfile
    image: phucngo249/class-service:latest
    container_name: class-service-app
    restart: always
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - DB_HOST=postgres-class-db
      - DB_PORT=5432
      - DB_NAME=class_service
      - DB_USER=postgres
      - DB_PASSWORD=123
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=supersecretpassword
      - MINIO_BUCKET=classroom-materials
      - APP_ALLOWED_ORIGINS=http://localhost:5173,http://192.168.66.133:5173
      - APP_JWT_SECRET=3c963655447b567565b90214e9f7f0bc62e1e07b7134017326dfbf0800b6ed5b
      - USER_SERVICE_URL=http://user-service
      - EUREKA_URL=http://discovery-service-app:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=class-service-app
    depends_on:
      postgres-class-db:
        condition: service_healthy
      minio:
        condition: service_started
      discovery-service:
        condition: service_healthy
    networks:
      - classroom-network

  assignment-service:
    build:
      context: .
      dockerfile: assignment_service/Dockerfile
    image: phucngo249/assignment-service:latest
    container_name: assignment-service-app
    restart: always
    ports:
      - "8083:8083"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - DB_HOST=postgres-assignment-db
      - DB_PORT=5432
      - DB_NAME=assignment_service
      - DB_USER=postgres
      - DB_PASSWORD=123
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=supersecretpassword
      - MINIO_BUCKET=assignment-materials
      - APP_ALLOWED_ORIGINS=http://localhost:5173,http://192.168.66.133:5173
      - APP_JWT_SECRET=3c963655447b567565b90214e9f7f0bc62e1e07b7134017326dfbf0800b6ed5b
      - USER_SERVICE_URL=http://user-service
      - CLASS_SERVICE_URL=http://class-service
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - EUREKA_URL=http://discovery-service-app:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=assignment-service-app
    depends_on:
      postgres-assignment-db:
        condition: service_healthy
      minio:
        condition: service_started
      discovery-service:
        condition: service_healthy
      broker:
        condition: service_started
      schema-registry:
        condition: service_started
    networks:
      - classroom-network

  notification-service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    image: phucngo249/notification-service:latest
    container_name: notification-service-app
    restart: always
    ports:
      - "8084:8084"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - EUREKA_URL=http://discovery-service-app:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=notification-service-app
    depends_on:
      discovery-service:
        condition: service_healthy
      broker:
        condition: service_started
      schema-registry:
        condition: service_started
    networks:
      - classroom-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-server
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - classroom-network

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - classroom-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    restart: always
    ports:
      - "8085:8081"
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - classroom-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-dashboard
    restart: always
    ports:
      - "8086:8080"
    depends_on:
      - broker
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - classroom-network

volumes:
  postgres_user_data:
  postgres_class_data:
  postgres_assignment_data:
  minio_data:

networks:
  classroom-network:
    name: classroom-network
    driver: bridge